# Site settings
title: HD LAB
email: hdlabconicet@gmail.com
author: HD LAB 
description: Sitio del Laboratorio de Humanidades Digitales (HD LAB) del Consejo Nacional de Investigaciones Científicas y Técnicas (CONICET)
baseurl: ""
url: "https://hdcaicyt.github.io"
twitter_username: hdlabconicet
github_username:  hdcaicyt
facebook_username: HDLAB.CONICET

# SEO PLUGIN
social:
  name: HD LAB
  links:
    - https://twitter.com/hdlabconicet
    - https://www.facebook.com/HDLAB.CONICET
    - https://github.com/hdcaicyt

# THEME SETTINGS
# navigation:
#   - {name: 'Novedades', link: '/novedades'}
#   - {name: 'Investigación', link: '/investigacion'}
#   - {name: 'Biblioteca Digital', link: '/biblioteca-digital'}
#   - {name: 'Equipo', link: '/equipo'}
#   - {name: 'Contacto', link: '/contacto'}
#   - {name: 'Buscar', link: '/search'}


tagline: >
  Laboratorio de Humanidades Digitales del CONICET

hero_img: posts/HDCAICYTLAB.jpg

disqus:
  shortname: hdtlab

# Build settings
markdown: kramdown
encoding: utf-8

collections:
  argentina_manuscrita: 
    output: true
  argentina_manuscrita_pages: 
    output: true

remote_theme: jekyll-sleek
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - script
  - package.json
  - package-lock.json
  - vendor
  - npm-debug.log
  - gulpfile.js

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
